FROM ollama/ollama:latest

WORKDIR /app
RUN apt-get update && apt-get install -y wget

COPY webapp/ollama/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 11434

ENTRYPOINT ["/entrypoint.sh"]
