FROM python:3.11-slim

RUN apt-get update && apt-get install -y wget
WORKDIR /app

COPY webapp/chainlit /app/webapp/chainlit
RUN pip install --upgrade pip
RUN pip install --no-cache-dir chainlit httpx

EXPOSE 8000

ENTRYPOINT ["chainlit", "run", "webapp/chainlit/app.py", "--host", "0.0.0.0", "--port", "8000"]
